### ISSUE TITLE
v2ray_softfloat failed to start but v2ray_softfloat_json works well

### ISSUE THREAD

**Issue by PandaBig** [felix-fly/v2ray-openwrt#1]
./v2ray_softfloat -config=config.pb -format=pb -test
V2Ray 4.19 (Po) Custom
A unified platform for anti-censorship.
main: failed to create server > Serial: Unknown type: v2ray.core.proxy.dokodemo.Config

./v2ray_softfloat_json -config=config.pb -format=pb -test
V2Ray 4.19 (Po) Custom
A unified platform for anti-censorship.
Configuration OK.

hardware information:
主机型号	Phicomm PSG1208
架构	MediaTek MT7620A ver:2 eco:6
固件版本	OpenWrt 18.06.2 r7676-cddd7b4c77 / LuCI openwrt-18.06 branch (git-19.020.41695-6f6641d)
内核版本	4.14.95

**Comment by felix-fly** [comment]
The dokodemo was missing on this build. I'll rebuild it.

**Comment by felix-fly** [comment]
You can try the new release app.

**Comment by PandaBig** [comment]
I've tried the new one, it's perfect now. Thanks!
