### ISSUE TITLE
v2ray关闭后无法上网

### ISSUE THREAD

**Issue by SenLief** [felix-fly/v2ray-openwrt#13]
v2ray开启后确实可以用，但是stop就不能上网了，好像是DNS有问题，这正常嘛。

**Comment by felix-fly** [comment]
关了要把防火墙规则也去掉

**Comment by SenLief** [comment]
这个有些麻烦额，有没有其他解决办法啥的。我看自带的那种是自动处理了吗？

发自我的华为手机


-------- 原始邮件 --------
发件人： Felix <notifications@github.com>
日期： 2020年2月11日周二 下午4:47
收件人： felix-fly/v2ray-openwrt <v2ray-openwrt@noreply.github.com>
抄送： SenLief <zjanence@gmail.com>, Author <author@noreply.github.com>
主 题： Re: [felix-fly/v2ray-openwrt] v2ray关闭后无法上网 (#13)

关了要把防火墙规则也去掉

―

**Comment by felix-fly** [comment]
自带的应该用脚本处理好了，你可以尝试我的[另外一种方式](https://github.com/felix-fly/v2ray-dnsmasq-dnscrypt)，不开启时其他的也可以上网
