### ISSUE TITLE
最新4.22.1 似乎不支持tls 1.3

### ISSUE THREAD

**Issue by inpot** [felix-fly/v2ray-openwrt#17]
我的v2ray仅支持tls1.3，4.22.1(4.22.0同样)报错无法连接，
** remote error: tls: protocol version not supported] > v2ray.com/core/common/retry: all retry attempts failed**
能检查一下是tls 1.3相关的编译配置不正确吗？

**Comment by felix-fly** [comment]
是go的版本影响的，已经修复，重新下载即可

**Comment by inpot** [comment]
辛苦了。

**Comment by inpot** [comment]
你能更新一下4.22.1 的release吗？

**Comment by felix-fly** [comment]
文件已经替换过了

**Comment by inpot** [comment]
辛苦了。。下载测试ok,  release页面上写的released this on 17 Feb， 我以为还没有更新。。我的错。
