### ISSUE TITLE
mipsle的版本4.22.1開始無法執行(4.21.3前版本可以)

### ISSUE THREAD

**Issue by kousyougi** [felix-fly/v2ray-openwrt#20]
我的路由器是Newifi mini Y1，CPU‎: ‎MediaTek MT7620A。
用Openwrt官網的19.07.02。
`https://downloads.openwrt.org/releases/19.07.2/targets/ramips/mt7620/`

剛剛測試4.23.1、4.22.1，都會出現下面錯誤訊息。然後跑4.21.3、4.20.0、4.19.1都可正常執行。
都是跑softfloat的程式。

V2Ray 4.23.1 (user) 20200330-095530 (go1.14 linux/mipsle)
A unified platform for anti-censorship.
2020/05/04 03:45:05 Using config from env:  /etc/config/v2ray/config.json
2020/05/04 03:45:05 [Info] v2ray.com/core/main/jsonem: Reading config: /etc/config/v2ray/config.json
SIGILL: illegal instruction
PC=0x89d60 m=0 sigcode=128

goroutine 1 [running]:
runtime.asyncPreempt()
        /usr/local/go/src/runtime/preempt_mipsx.s:40 +0x7c fp=0x18fdae8 sp=0x18fd9f4 pc=0x89d60
v2ray.com/core/common/uuid.ParseString(0x192a7e0, 0x24, 0x0, 0x0, 0x0, 0x0, 0x1a5d8, 0x1814000)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/uuid/uuid.go:67 +0x5c fp=0x18fdb78 sp=0x18fdaec pc=0x249f38
v2ray.com/core/proxy/vmess.(*Account).AsAccount(0x190efc0, 0xa56980, 0x190efc0, 0x6fdb2d50, 0x190efc0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/proxy/vmess/account.go:41 +0x48 fp=0x18fdbcc sp=0x18fdb78 pc=0x697490
v2ray.com/core/common/protocol.(*User).GetTypedAccount(0x190ed40, 0x2509b8, 0x2509f4, 0x8, 0x7fd680)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/protocol/user.go:13 +0x238 fp=0x18fdc00 sp=0x18fdbcc pc=0x251b10
v2ray.com/core/common/protocol.(*User).ToMemoryUser(0x190ed40, 0x1, 0x1, 0x190a5c0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/protocol/user.go:22 +0x3c fp=0x18fdc20 sp=0x18fdc00 pc=0x251c8c
v2ray.com/core/common/protocol.NewServerSpecFromPB(0x190ed20, 0x1bb, 0x190a568, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x184be40, ...)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/protocol/server_spec.go:65 +0xc8 fp=0x18fdc54 sp=0x18fdc20 pc=0x250a44
v2ray.com/core/proxy/vmess/outbound.New(0xa581c0, 0x190ea60, 0x190eba0, 0x122, 0x3, 0x18678ec)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/proxy/vmess/outbound/outbound.go:39 +0xe4 fp=0x18fdcd8 sp=0x18fdc54 pc=0x6a9d98
v2ray.com/core/proxy/vmess/outbound.init.2.func1(0xa581c0, 0x190ea60, 0x8e7840, 0x190eba0, 0x8e7801, 0xa56a00, 0x47e040, 0x18ee200)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/proxy/vmess/outbound/outbound.go:184 +0x64 fp=0x18fdcf4 sp=0x18fdcd8 pc=0x6ac008
v2ray.com/core/common.CreateObject(0xa581c0, 0x190ea60, 0x8e7840, 0x190eba0, 0x0, 0x897015bc, 0x190a4e0, 0x47d2dc)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/type.go:32 +0x228 fp=0x18fdd38 sp=0x18fdcf4 pc=0x1b1288
v2ray.com/core/app/proxyman/outbound.NewHandler(0xa581c0, 0x190ea60, 0x1910210, 0xfb5e0f01, 0xf3d4fb, 0x1, 0x1867a30)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/app/proxyman/outbound/handler.go:61 +0x158 fp=0x18fdd98 sp=0x18fdd38 pc=0x47e084
v2ray.com/core/app/proxyman/outbound.init.0.func2(0xa581c0, 0x190ea60, 0x8f8da0, 0x1910210, 0x266201, 0x1104ec, 0x20, 0x8cc220)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/app/proxyman/outbound/outbound.go:168 +0x64 fp=0x18fddb8 sp=0x18fdd98 pc=0x480c0c
v2ray.com/core/common.CreateObject(0xa581c0, 0x190ea60, 0x8f8da0, 0x1910210, 0x8cb5c0, 0x1910240, 0xa581c0, 0x190ea60)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/type.go:32 +0x228 fp=0x18fddfc sp=0x18fddb8 pc=0x1b1288
v2ray.com/core.CreateObject(0x1910240, 0x8f8da0, 0x1910210, 0x6fdb2b78, 0x184b980, 0x0, 0x0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/functions.go:21 +0x68 fp=0x18fde20 sp=0x18fddfc pc=0x263d9c
v2ray.com/core.AddOutboundHandler(0x1910240, 0x1910210, 0x0, 0x0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/v2ray.go:125 +0xa4 fp=0x18fde4c sp=0x18fde20 pc=0x264b68
v2ray.com/core.addOutboundHandlers(0x1910240, 0x190a388, 0x1, 0x2, 0x0, 0x0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/v2ray.go:141 +0x78 fp=0x18fde68 sp=0x18fde4c pc=0x264d78
v2ray.com/core.New(0x187f860, 0x4, 0x18244c0, 0x1d)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/v2ray.go:211 +0x2e4 fp=0x18fdef4 sp=0x18fde68 pc=0x265138
main.startV2Ray(0x1854060, 0x180c100, 0x0, 0x0)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/main/main.go:121 +0x300 fp=0x18fdf4c sp=0x18fdef4 pc=0x7aa670
main.main()
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/main/main.go:146 +0xb8 fp=0x18fdfc0 sp=0x18fdf4c pc=0x7aa9fc
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x284 fp=0x18fdfec sp=0x18fdfc0 pc=0x51048
runtime.goexit()
        /usr/local/go/src/runtime/asm_mipsx.s:651 +0x4 fp=0x18fdfec sp=0x18fdfec pc=0x895e0

goroutine 6 [select]:
v2ray.com/core/common/log.(*generalLogger).run(0x180a040)
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/log/logger.go:54 +0x19c
created by v2ray.com/core/common/log.(*generalLogger).Handle
        /home/runner/work/v2ray-openwrt/v2ray-openwrt/v2ray-core/common/log/logger.go:77 +0xc0

r0   0x0        r1   0x55
r2   0x18fdb43  r3   0x192a7e0
r4   0x1d5      r5   0x8f73e0
r6   0x4        r7   0x6fdb2d50
r8   0x0        r9   0x1914c00
r10  0x0        r11  0x0
r12  0x18       r13  0x1916648
r14  0x191665c  r15  0x0
r16  0x1        r17  0x0
r18  0x8        r19  0x0
r20  0x190efc0  r21  0x190efe0
r22  0x94e574   r23  0x4
r24  0x65663931 r25  0x0
r26  0x0        r27  0x0
r28  0x8a13230d r29  0x18fd9f4
r30  0x18000e0  r31  0x249f38
pc   0x89d60    link 0x249f38
lo   0x0        hi   0x0

謝謝

**Comment by felix-fly** [comment]
应该是go的版本有bug，升级到最新的重新编译了4.23.1，你试试

**Comment by kousyougi** [comment]
可以用了
謝謝
