### ISSUE TITLE
v2ray-openwrt CPU持续 10%占用

### ISSUE THREAD

**Issue by q629988171** [felix-fly/v2ray-openwrt#23]
环境说明：
主机型号	HiWiFi HC5962
架构	MediaTek MT7621 ver:1 eco:3
固件版本	OpenWrt 18.06.8 r7989-82fbd85747 / LuCI openwrt-18.06 branch (git-20.029.49294-41e2258)
v2ray 4.24.2

故障现象：CPU持续 10%占用

故障原因：
luci-app-v2ray 需要显示版本信息，就会调用这个命令来获取版本信息

/usr/bin/v2ray --version 无法显示版本信息，导致不停的调用

换成原版v2ray 没有此问题

**Comment by felix-fly** [comment]
那要把v2ray放到/usr/bin/v2ray才能匹配上luci-app-v2ray的命令

**Comment by q629988171** [comment]
> 那要把v2ray放到/usr/bin/v2ray才能匹配上luci-app-v2ray的命令

v2ray放到/usr/bin/v2ray，指的是/usr/bin/v2ray 还是 /usr/bin/v2ray/v2ray，我目前放在的是 /usr/bin/v2ray

我直接在 ssh 里，执行 /usr/bin/v2ray --version 无法显示版本信息

**Comment by felix-fly** [comment]
> /etc/config/v2ray/v2ray --version
> V2Ray 4.24.2 (user) 20200611-120941 (go1.14.4 linux/arm64)
> A unified platform for anti-censorship.
我的设备上没问题，你的无法显示是报什么错吗

**Comment by q629988171** [comment]
> > /etc/config/v2ray/v2ray --version
> > V2Ray 4.24.2 (user) 20200611-120941 (go1.14.4 linux/arm64)
> > A unified platform for anti-censorship.
> 
> 我的设备上没问题，你的无法显示是报什么错吗

没有任何报错，执行没有任何结果，光标一直在闪烁（没有执行完成）

root@OpenWrt:/tmp# ./v2ray_softfloat --version

■

**Comment by felix-fly** [comment]
是upx的问题 [https://github.com/upx/upx/issues/342](https://github.com/upx/upx/issues/342)
暂时先用3.94的，你下载4.25.0的试试看吧

**Comment by q629988171** [comment]
> 是upx的问题 [upx/upx#342](https://github.com/upx/upx/issues/342)
> 暂时先用3.94的，你下载4.25.0的试试看吧

经过测试，故障解决

root@OpenWrt:/tmp# ./v2ray_softfloat --version
V2Ray 4.25.0 (user) 20200622-022123 (go1.14.4 linux/mipsle)
A unified platform for anti-censorship.

**Comment by felix-fly** [comment]
解决就好
