### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by zlylong** [felix-fly/v2ray-openwrt#26]
pkg/mod/github.com/lucas-clemente/quic-go@v0.18.1/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate

**Comment by felix-fly** [comment]
这是什么

**Comment by zlylong** [comment]
> 这是什么

编译停止的日志。

**Comment by mrproliu** [comment]
更新go的版本号到1.14或者以上就可以了
