### ISSUE TITLE
V2Ray mipsle client error.

### ISSUE THREAD

**Issue by MrLimb** [felix-fly/v2ray-openwrt#4]
Hello! I try to run my client config and get this:
main: failed to create server > v2ray.com/core/app/router: this rule has no effective fields.
(ws config) 
MT7621A

**Comment by felix-fly** [comment]
@MrLimb Maybe there some wrong in your configuration. Can you paste it here?

**Comment by MrLimb** [comment]
"Normal" V2Ray works fine with my configuration.

**Comment by MrLimb** [comment]
"Normal" V2Ray works fine with my configuration.

**Comment by carmineyiu** [comment]
Newifi3 应该选哪个release v2ray-linux-mips64， 还是 v2ray-linux-mips64le。 是不是下载 到 openwrt 客户端 直接运行？已能V2ray 客户端对 v2ray 服务端。 没有转DNS到 V2ray 服务端，觉得有点难，想找一个简单配置。
